### PR TITLE
GPU support

### PR DESCRIPTION
**Pull request by richfitz**
This PR depends on rather a lot of things that are in flight:

* https://github.com/mrc-ide/dust/pull/380
* https://github.com/mrc-ide/dust/pull/381
* https://github.com/mrc-ide/odin.dust/pull/120
* https://github.com/mrc-ide/odin.dust/pull/119
* https://github.com/mrc-ide/lostturnip/pull/1
* https://github.com/mrc-ide/lostturnip/pull/2
* https://github.com/mrc-ide/dust/pull/382
* https://github.com/mrc-ide/dust/pull/383
* https://github.com/mrc-ide/odin.dust/pull/121

I fear we're well beyond the point where pak can reliably build the dependencies here, so expect things to fail until that's all merged.

~Contains commits from #3, merge after that.~

It does look like we might be ok in terms of running the model on the GPU, preliminary checks suggest that performance is reasonable too. ~There's an issue in the filter that needs resolving though, currently we fail there returning -Inf always~

~This will be slightly nicer to document and merge if we can come up with a better name for m4_2~

### CODE REVIEW

**Comment by richfitz** [comment]
```r
## This is largely working I think, except that the compare/filter is
## incorrect and failing to calculate properly (returning
## -Inf). Bisecting in on this requires that I sort out some of the
## outstanding work in the underlying packages, I think.
gpu <- dust::dust_cuda_options(fast_math = TRUE, profile = FALSE,
                               quiet = FALSE, debug = FALSE)

pkgload::load_all()
gen_gpu <- monkeyspam:::compile_gpu(
  verbose = TRUE, real_type = "float", workdir = "gpu", gpu = gpu)
gen_cpu <- monkeyspam:::compile_gpu(
  verbose = TRUE, real_type = "float", gpu = FALSE, gpu_generate = TRUE)

data <- filter_data()
pars <- reference_pars()
n_particles <- 128

mod_cpu <- gen_cpu$new(list(), 1, n_particles, seed = 1L)
mod_gpu <- gen_gpu$new(list(), 1, n_particles, seed = 1L, gpu_config = 0L)

t <- c(1, seq(7, 196, by = 7))
nms <- names(mod_cpu$info()$index)

y_cpu <- mod_cpu$simulate(t)
y_gpu <- mod_gpu$simulate(t)

rownames(y_cpu) <- nms
rownames(y_gpu) <- nms

compare <- function(name, y_cpu, y_gpu) {
  ylim <- range(y_cpu[name, , ], y_gpu[name, , ], na.rm = TRUE)
  matplot(t(y_cpu[name, , ]), lty = 1, col = "#ff000055", lwd = 0.5,
          type = "l", main = name, ylim = ylim)
  matlines(t(y_gpu[name, , ]), lty = 1, col = "#0000ff55", lwd = 0.5)
}

unlink("plot", recursive = TRUE)
dir.create("plot", FALSE, TRUE)
png("plot/compare-%02d.png", width = 800, height = 600)
for (name in nms) {
  compare(name, y_cpu, y_gpu)
}
dev.off()
```

Not currently working, looks like many trajectories are failing to move at all, so something is catastrophically wrong.

**Comment by richfitz** [comment]
The error comes from the poisson draws, see https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-3841 for details

**Comment by richfitz** [comment]
Draws working now. Get this up and running with:

```
gpu <- dust::dust_cuda_options(fast_math = TRUE, profile = FALSE,
                               quiet = FALSE, debug = FALSE)

pkgload::load_all()
gen <- monkeyspam:::compile_gpu(
  verbose = TRUE, real_type = "float", workdir = "gpu", gpu = gpu)

data <- filter_data()
pars <- reference_pars()
n_particles <- 128

mod_cpu <- gen$new(list(), 1, n_particles, seed = 1L)
mod_gpu <- gen$new(list(), 1, n_particles, seed = 1L, gpu_config = 0L)

t <- c(1, seq(7, 196, by = 7))
nms <- names(mod_cpu$info()$index)

y_cpu <- mod_cpu$simulate(t)
y_gpu <- mod_gpu$simulate(t)

rownames(y_cpu) <- nms
rownames(y_gpu) <- nms

compare <- function(name, y_cpu, y_gpu) {
  ylim <- range(y_cpu[name, , ], y_gpu[name, , ], na.rm = TRUE)
  matplot(t(y_cpu[name, , ]), lty = 1, col = "#ff000055", lwd = 0.5,
          type = "l", main = name, ylim = ylim)
  matlines(t(y_gpu[name, , ]), lty = 1, col = "#0000ff55", lwd = 0.5)
}

unlink("plot", recursive = TRUE)
dir.create("plot", FALSE, TRUE)
png("plot/compare-%02d.png", width = 800, height = 600)
for (name in nms) {
  compare(name, y_cpu, y_gpu)
}
dev.off()

n_particles <- 2^12
f_cpu <- m4_2_filter(data, model = gen, n_particles = n_particles,
                     use_compiled_compare = TRUE, n_threads = 8, seed = 1L)
t_cpu <- replicate(10, system.time(f_gpu$run(pars))[["elapsed"]])


t_gpu <- list()
nn <- 10:18
for (n in 10:18) {
  f_gpu <- m4_2_filter(data, model = gen, n_particles = 2^n,
                       use_compiled_compare = TRUE, n_threads = 8, seed = 1L,
                       gpu_config = list(device_id = 0L, block_size = 256))
  t_gpu[[as.character(n)]] <-
    replicate(10, system.time(f_gpu$run(pars))[["elapsed"]])
}

tt_gpu <- vapply(t_gpu, mean, numeric(1))

## To get things up to a single metric, we scale into time per million
## particles. For comparison, pomp is 206s f0r 5000 particles =
## 41200s/million particles.
plot(nn, tt_gpu / (2^nn / 1e6), type = "o", pch = 19, log = "y")
abline(h = mean(t_cpu) / (2^12 / 1e6))
```

Probably some work do to here to check that we have optimal block size and number of registers. I'd like to get a profile done too.

**Comment by richfitz** [comment]
Getting there - there's still a bit of f64 to squash out; perhaps abs and ceil are the culprits? 

```
gpu <- dust::dust_cuda_options(fast_math = TRUE, profile = FALSE,
                               quiet = FALSE, debug = TRUE,
                               flags = "-Xptxas -warn-double-usage -src-in-ptx")
pkgload::load_all()
gen <- mpoxspam::compile_gpu(
  verbose = TRUE, real_type = "float", workdir = "gpu", gpu = gpu)
```

**Comment by richfitz** [comment]
With updated deps now, the remaining f64 math is gone

**Review by lwhittles — APPROVED** [review]
👋

**Pull request merged**
